### ISSUE TITLE
整理并输出开源社各小组成员列表

### ISSUE THREAD

**Issue by zhuangbiaowei** [kaiyuanshe/tasks#1]
|小组名称|小组成员|一句话简介|主要承担的工作|
|----------|----------|----------|----------|
|||||

大致按照以上格式

**Comment by WallaceOS** [comment]
法律事务组

梁   尧 | 关注于开源治理和专利法研究 | 负责法律事务组工作的组织开展。
薛   亮 | 关注于开源软件知识产权问题研究 | 开展开源许可证等开源规则研究及案例分析，推动打造开源事务智库平台。
董振伟 | 关注于开源许可证和开源参与者动机研究 | 与其他工作组协调开展落实相关开源文献翻译工作。

**Comment by juniwang** [comment]
基础设施工作组

王俊波|微软软件工程师|基础设施组日常工作，同时参与开发运维等
王春生|蝉道创始人|开源社推广及运维
管西迎|蝉道软件工程师|开源社网站开发及管理
史璞金|在校学生,linux人社区管理员|开源社网站开发及管理，拟参与区块链开发。
李丹|用户体验设计师，kaiyuanshe logo设计者|暂无具体工作，拟参与将来的设计类相关工作。
孟一凡|百度算法工程师|暂无具体工作
余杰|暂无具体工作

**Comment by frank-zsy** [comment]
高校合作工作组

赵生宇|网易|高校开源社团联系
Limy|优麒麟|原开源大使成员联系
汪盛|华为|高校校方开源负责人联系
李思颖|微软|高校合作相关文章发布
舒敏|高校合作方案具体实施

**Comment by cynbarby** [comment]
媒体组

李思颖 | 媒体组日常工作维护与成员发展
董振伟 | 内容品控 
孙远 | 赢在开源系列 主创
晁倩 | 品牌运营
刘亚萌非 | 品牌运营
舒敏 | 微信公众号内容运营 + 微博内容运营
张曼Mandy | 微信公众号内容运营 + FB/TW内容运营
张婷婷 | 微信公众号内容运营 + 设计品控
王兴宇 | Linux 中国 与 开源社 媒体组 平台对接联系人（暂）
Richard | FB/TW 内容运营 （指导）

**Comment by tedliu1** [comment]
在石墨创建了一个表格，方便大家填写
https://shimo.im/sheet/s0qLXQ2HPvUbZrSv

**Comment by TechQuery** [comment]
## 工作组

- 数据：https://kaiyuanshe.feishu.cn/base/bascnUAyhKLADcw3HyNW5OefrMd?table=tbl9sqVJxIdLIdUC&view=vewdErGNvQ
- 代码：kaiyuanshe/kaiyuanshe.github.io#68
- 页面：https://test.kaiyuanshe.cn/department

## 正式成员

- 数据：https://kaiyuanshe.feishu.cn/base/bascnUAyhKLADcw3HyNW5OefrMd?table=tblXwXvalJSspqkR&view=vewFNht7jN
- 代码：kaiyuanshe/kaiyuanshe.github.io#70

## 志愿者

- 数据：https://kaiyuanshe.feishu.cn/base/bascnUAyhKLADcw3HyNW5OefrMd?table=tblsX2KDkoOeubHv&view=vewoRmeTgW
