### ISSUE TITLE
Merge ossstar into Kaiyuanshe website

### ISSUE THREAD

**Issue by juniwang** [kaiyuanshe/tasks#4]
Currently the two components are independant and deployed in two cloud services. We can merge them into one to economize.

**Comment by shipujin** [comment]
Received

**Comment by TechQuery** [comment]
## 数据源

1. https://kaiyuanshe.feishu.cn/base/UaJ6b4MtcaywOwsaT7ecyiQuntc?table=tblpIuqXWETOtI2p&view=vewl4n6gCx
2. https://kaiyuanshe.feishu.cn/docx/TKuGdFFfDoc6c6xmRwscWrptnKg?from=from_parent_docs

## API

参考 kaiyuanshe/kaiyuanshe.github.io#88
